### ISSUE TITLE
Provide option to use synchronized version of jexl

### ISSUE THREAD

**Issue by raymondsze** [TechnologyAdvice/Jexl#10]
It would be better if I can choose either async or sync evaluation of jexl by option/ config. For example, I want to evaluate a json object with special syntax "${...}", eg. ${"2016-4-15"|toDate} where toDate is custom transform I added to jexl. I would grab the context between ${ and } by regular expression. The final object derived would be a Date object.
I would like to do this on React Component where the above would be one of the props, as the React Component lifecycle function is not async, I would like to do it and convert the props to state and use the state for the first time rendering. 
I think it is just example case, there are many cases we may want to use Sync instead of Async.
Maybe can follow fs, jexl.evalSync and jexl.eval?

**Comment by TomFrost** [comment]
Jexl is Promises-based internally as well as externally; I'm afraid that with that design, synchronous evaluations are currently impossible. I could see a potential solution (if Jexl's evaluator were completely rewritten) that would allow for Promises to be detected and throw an exception if one is encountered in a synchronous evaluation call, but the hackiness of such a thing makes me cringe a bit.

It's probably better to think of Jexl as any other asynchronous data source, like an http request, and have its result trigger an action that populates the React component. Due to the user (you) being in control of whether a Jexl expression requires external I/O, any content necessary on initial pageload can appear without perceptible delay.

If it _must_ be synchronous, I'm afraid the better solution for now would be to turn to an evaluator that doesn't have support for async transforms -- many template languages function this way. I'll keep chewing on this problem, though, for a potential 2.0 release.

**Comment by TomFrost** [comment]
Revisiting this ticket almost a year later, I think there's no hope for a synchronous version. Doing so would require dropping support for Promises/asynchronous transforms and operators, and I think it's more of a problem to drop such a huge range of functionality from Jexl than it is to write code that expects an asynchronous response. Apologies if that's difficult for your use case.

Although if you're in Node, async/await is quite nice for Jexl!

**Comment by michaelmior** [comment]
It seems like now the `evalSync` function supports synchronous evaluation unless I'm missing something. (I'm new to jexl)

**Comment by TomFrost** [comment]
@michaelmior You're absolutely right -- this ticket closed two and a half years ago and I didn't think to update it once sync support was actually delivered. But for anyone finding this via google: Jexl now supports synchronous evaluation, as long as you don't add and call any asynchronous transforms or operators. See `evalSync` in the README for details!
