### ISSUE TITLE
interceptor

### ISSUE THREAD

**Issue by devmondo** [TechnologyAdvice/Jexl#20]
Hi, 
can we have feature to intercept the expression before evaluating it, so we can do custom operations on it?

thanks in advanced.

**Comment by TomFrost** [comment]
Hey devmondo, I was just cleaning up old issues and realized I never responded to this one.

Since this is javascript, would simply monkey-patching a new `jexl.eval` do the trick for you? This seems like a pretty specialized need that doesn't need to be addressed directly, but what you're looking for should be quite each to achieve with a simple override.

**Comment by devmondo** [comment]
@TomFrost  thanks for the answer, if this can be done and it is good and not big trouble for you, ya sure :)
we are using angular-expressions now and was hoping to jump to jexel, hope v2 would be good too :)

**Comment by TomFrost** [comment]
Oh, my suggestion was handling it in _your_ code :)  What I meant was handling this in one of two ways-- writing a simple wrapper and calling it instead (forgive me, not ultra familiar with Angular, so I'm sure there's syntax to be wrapped around this that I don't have):

```javascript
const jexl = require('jexl')

const evalExpr = (expr, context) => {
  // Do whatever you gotta do
  return jexl.eval(expr, context)
}
```

Or just monkey-patch Jexl itself, and you can continue referencing Jexl directly:

```javascript
jexl._origEval = jexl.eval

jexl.eval = (expr, context) => {
  // Do whatever you gotta do
  return jexl._origEval(expr, context)
}
```

Does this cover your need?

**Comment by devmondo** [comment]
thank you this is sound perfect :)
