### ISSUE TITLE
Dates and times

### ISSUE THREAD

**Issue by erotavlas** [TechnologyAdvice/Jexl#23]
Does this library handle the comparison of date, and times?
for example 

```
var context = {
    birthdate: "01-01-1975',
    todaysdate: '25-03-2017'
}
jexl.eval('birthdate < todaysdate', context).then(function(res){ });
```

**Comment by TomFrost** [comment]
In this case, you are comparing strings because there's nothing in the expression to indicate you'd rather treat it as a time. However, this is quite easy to add :) Please test before using, but I'd suggest something like this:

```javascript
jexl.addTransform('toEpoch', (dateStr) => {
  return new Date(dateStr).getTime()
})
```

Now this will work:

```javascript
var context = {
    birthdate: "01-01-1975',
    todaysdate: '03-25-2017'
}
jexl.eval('birthdate|toEpoch < todaysdate|toEpoch', context).then(function(res){ });
```

Note that, for that specific solution, you'd need to provide dates that the javascript Date object can parse -- so I had to change `todaysdate` to MM-DD-YYYY format rather than DD-MM-YYYY. But you can support your own format just by splitting on the `-` and instantiating `Date` however you want.

If you don't like the syntax of having to apply a transform to every date, you could also add a binary operator that assumes that both the left and right sides are dates.  If you wanted the symbol for "date less than" to be `<d<` (just picking something out of thin air for example -- make that whatever you want), you could do this:

```javascript
jexl.addBinaryOp('<d<', 20, function(left, right) {
  return new Date(left).getTime() < new Date(right).getTime()
})
```

And now you can do this:

```javascript
var context = {
    birthdate: "01-01-1975',
    todaysdate: '03-25-2017'
}
jexl.eval('birthdate <d< todaysdate', context).then(function(res){ });
```

Personally, I think the transform option, while more verbose, is the cleaner option here, but it's up to you :)

**Comment by erotavlas** [comment]
Thanks for pointing out the transform, I never considered that.

Regarding the custom binary operator, is there any restriction or rules we must follow when adding our own?  For instance in your example above you created one like <d<, but does the parser know to treat the entire unit as an operator and not stop at the first < and treat that as a less than operator which is registered already?

At first I thought custom operators had to start with underscore like _= because of the example on the main page.

**Comment by TomFrost** [comment]
Oh, nope! The `_=` was completely arbitrary. It could have been `=_` or `=<` or `***` and it would have worked all the same. Jexl performs longest-first tokenization, meaning that it will check for `<d<` _before_ checking for `<`.

**Comment by erotavlas** [comment]
I'm a bit unclear on the use of transform (i.e. the syntax for passing parameters.

So from your example 

> jexl.addTransform('toEpoch', (dateStr) => {
>   return new Date(dateStr).getTime()
> })

Does this mean toEpoch is the transform function which takes one parameter called dateStr - and this first (and only) parameter comes from the value preceding the pipe symbol in the expression birthdate|toEpoch
Is that right?

Now if I want to add a second parameter like this

> jexl.addTransform('toEpoch', (dateStr, format) => {
>   return new Date(dateStr).getTime()
> })
> 

Then do I have to call the toEpoch like in the example on the main page

> // Transform asynchronously, with arguments
> jexl.addTransform('getStat', function(val, stat) {
>     return dbSelectByLastName(val, stat); // Returns a promise
> });
> jexl.eval('name.last|getStat("weight")', context, function(err, res) {
>     if (err) console.log('Database Error', err.stack);
>     else console.log(res); // Output: 184
> });

So myDate|toEpoch("MM-DD-YYYY")

Where the first parameter is always assumed to be the value on the left side of the pipe?

**Comment by TomFrost** [comment]
You're exactly right. Every transform function will be called with a minimum of one argument, and that first argument is always the subject being transformed (the left of the pipe). Any additional arguments to the transform function are what the user specified in parens after the transform name.
