### ISSUE TITLE
Path after array filter results single entry?

### ISSUE THREAD

**Issue by asaf** [TechnologyAdvice/Jexl#8]
Hey,

Considering this:

```js
const jexl = require('jexl');

var context = {
    name: {first: 'Sterling', last: 'Archer'},
    assoc: [
        {first: 'Lana', last: 'Kane'},
        {first: 'Lana', last: 'Kane1'},
        {first: 'Cyril', last: 'Figgis'},
        {first: 'Pam', last: 'Poovey'}
    ],
    age: 36
};

const exp = 'assoc["Lana" in .last]';
```

Evaluating this expression results `Kane`, I was expecting the filter to result two objects and then extract from both the last name: `["Kane", "Kane1"]`

(btw, without data extraction after filter it does result two objects)

Thoughts?

Thanks.

**Comment by TomFrost** [comment]
That's intentional-- it was put in place as a convenience shorthand. If you attempt to access a property of a collection, Jexl assumes you want the first index. You're correct, though: if you don't access a property, you can treat the collection as any other array.  For example:

```javascript
await jexl.eval('assoc["Kane" in .last]', context) // [ { first: 'Lana', last: 'Kane' }, { first: 'Lana', last: 'Kane1' } ]
await jexl.eval('assoc["Kane" in .last].last', context) // "Kane"
await jexl.eval('assoc["Kane" in .last][0].last', context) // "Kane" -- semantically the same as the above
await jexl.eval('assoc["Kane" in .last][1].last', context) // "Kane1"
```

We're pulling together some feature requests for a v2.0.0 release, though, which can include minor breaking changes. If this default functionality breaks something you're trying to do, I'd love to hear more about your use case so that we can consider eliminating this in the future.

**Comment by asaf** [comment]
Hey,

Logically I was expecting it to act like a filter -> map logic, what is the rationale behind this intended behavior ?

**Comment by TomFrost** [comment]
By filter -> map, do you mean you would expect the expression `assoc["Kane" in .last].last` to result in `["Kane", "Kane1"]`?

If so, that's currently beyond the scope of Jexl as it would result in exponentially increased processing. The remainder of the expression after a filter would need to be applied to each of an array of values instead of just one (including any potentially expensive transforms), and two filters in a row of a nested collection would quickly make that untenable. By far the more common use case we've seen is in applying a filter and wanting to work with only the first result, a la throwing a `LIMIT 1` at the end of an SQL query. But this implementation makes the full result set available if it's of use.

It's worth noting that, for those who DO have the use case above, it can be achieved with a custom one-line transform that simply returns the result of lodash's `.pluck()` method.

**Comment by asaf** [comment]
@TomFrost Thanks for clarifying this out,

I just found it confusing but I understand the rational behind limiting the scope of Jexl while maintaining high performance

Piping transformers covers this use case anyway so it's alright,

Closing, 

Thanks again!

**Comment by ctapobep** [comment]
@TomFrost, having tried jsonpath, jspath, xpath - the functionality of Jexl seems like an exception. Was very confusing/frustrating to realize it didn't behave same way as others. Can't think of a situation where I'd ignore all other entries which satisfy the filter.. 

Anyway, this probably won't be changed, so question is: is there a way to override this behaviour w/o custom transforms? If not, could you point to the piece of code that I'd have to change in case I decide to fork this repo for my own use case?

I'd like to expose an EL to my users, but I don't want to make them add a transform in each expression.
